set -g default-terminal "screen-256color"

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-option -g status-left-length 50

set-option -sg escape-time 10

set-option -g detach-on-destroy off

# Reload config
bind-key R source-file ~/.tmux.conf \; \
    display-message "source-file done"

# Create new session
bind-key N new-session -c '#{pane_current_path}' -s '#{b:pane_current_path}' \; \
    new-window -n git -t 1 \; \
    select-window -t:0

# Move around
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Last window (override by "select-pane -R")
bind-key u last-window

bind-key A new-session -c '/ts/data/workspace/catalog/specific/mc-b2c' -s 'mc-b2c' \; \
    new-session -c '/ts/data/workspace/distributor/macif/macif.platform.static' -s 'macif.platform.static' \; \
    new-session -c '/ts/data/workspace/platform/modules/distribution/orchestra-catalog-libs' -s 'orchestra-catalog-libs' \; \
    kill-session -t 0
