set -g default-terminal "screen-256color"

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-option -g status-left-length 50

set-option -sg escape-time 10

set-option -g detach-on-destroy off

# Reload config
bind-key R source-file ~/.tmux.conf \; \
    display-message "source-file done"

# Create new session
bind-key N new-session -c '#{pane_current_path}' -s '#{b:pane_current_path}' \; \
    new-window -n git -t 1 \; \
    select-window -t:0

# Move around
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Last window (override by "select-pane -R")
bind-key u last-window

# bind-key A new-session -c '/ts/data/workspace/devops/docker-images/docker-application-platform/docker-application-bookingprocess/' -s 'docker-application-bookingprocess' \; \
#     new-session -c '/home/emmanuelmollard/Document/Azul/' -s 'Azul' \; \
#     new-session -c '/ts/data/workspace/platform/connectivity/common/connectivity-ear/' -s 'connectivity-ear' \; \
#     new-session -c '/ts/data/workspace/platform/connectivity/common/nucleus.productbooking3.beans/' -s 'nucleus.productbooking3.beans' \; \
#     new-session -c '/ts/data/workspace/platform/connectivity/transport/azul.http.client/' -s 'azul.http.client' \; \
#     new-session -c '/ts/data/workspace/platform/connectivity/transport/nucleus.productbooking3.azul/' -s 'nucleus.productbooking3.azul' \; \
#     new-session -c '/ts/data/workspace/platform/modules/b2c/components/orchestra.bookingprocess.front' -s 'orchestra.bookingprocess.front' \; \
#     new-session -c '/ts/data/workspace/platform/static/shared/orchestra.global-shared.static' -s 'orchestra.global-shared.static' \; \
#     new-session -c '/ts/data/workspace/platform/static/tourcameleodev/tourcameleodev.transport-process.static' -s 'tourcameleodev.transport-process.static' \; \
#     new-session -c '/ts/data/workspace/platform/modules/b2c/bookingprocess' -s 'bookingprocess' \; \
#     kill-session -t 0

bind-key A \
    new-session -c '/ts/data/workspace/devops/docker-images/docker-application-platform/docker-application-bo' -s 'docker-application-bo' \; \
    new-session -c '/ts/data/workspace/platform/static/common/orchestra.shared.static' -s 'orchestra.shared.static' \; \
    new-session -c '/ts/data/workspace/platform/modules/backoffice/orchestra-bo-war' -s 'orchestra-bo-war' \; \
    new-session -c '/ts/data/workspace/platform/common/orchestra-commons-struts' -s 'orchestra-commons-struts' \; \
    new-session -c '/ts/data/workspace/platform/common/orchestra-commons' -s 'orchestra-commons' \; \
    kill-session -t 0
